### PR TITLE
Github link added to landing page

### PR DESCRIPTION
**Pull request by yashfalke77**
I have added the github link to the landing page with icon do checkout :) , if any improvisation needed then tell me

### CODE REVIEW

**Comment by michmich112** [comment]
@yashfalke77 Can you add screenshots for desktop view and mobile view?

**Comment by yashfalke77** [comment]
@michmich112  here are the screenshots: 

image

**Comment by michmich112** [comment]
@yashfalke77 Thanks for the screenshot!
Can you instead make it so that the user can just click on the icon to be redirected to the repo? 
No need for the link nor title to be visible.

After that should be ready to merge! :) 
Also feel free to join the discord if you would like to keep contributing and connect with others: https://discord.gg/WNsGB7gC

**Comment by yashfalke77** [comment]
@michmich112 ok i will create new pull request and will add it

**Comment by yashfalke77** [comment]
Hey @michmich112  updated it 

image

**Review by michmich112 — APPROVED** [review]

**Pull request merged**
